### ISSUE TITLE
trouble with amounts and smallcaps

### ISSUE THREAD

**Issue by dckc** [p2p-org/p2p-agoric-vstorage-viewer#7]
This widget is so useful! We're kinda addicted to it.

One of our testnets is running with the new smallcaps marshal format
https://github.com/Agoric/agoric-sdk/issues/6822

this tool doesn't seem to support it:

![image](https://github.com/p2p-org/p2p-agoric-vstorage-viewer/assets/150986/b8c8a91d-726d-4588-85f2-28653c28caac)

We may be interested to contribute a fix.

cc @turadg @warner

**Comment by alexesDev** [comment]
@dckc, thank you! I'm glad it was useful. You can uncheck the 'Fold amount objects' option to rectify the issue.
Additionally, I have merged PR #8.
